### ISSUE TITLE
Cannot find source code

### ISSUE THREAD

**Issue by OmarGonD** [dhmontgomery/personal-work#3]
Hi, great work.

I would like to see the source code for your theme. May you point me to it? thank you.

**Comment by dhmontgomery** [comment]
Hey Omar — as stated in the writeup, the theme itself was produced for an employer, who has decided (for now) to not publish the theme. They did give permission to share this writeup.

If you're interested in writing your own theme, you can see the structure by entering `theme_grey()` or `theme_minimal()` into your R console, then pasting the resulting text into a text editor for revisions.  That's how I got started writing this. (That, plus lots of trial and error.)

Your theme's structure, dropping a few things, should look like this: 

`theme_name <- function (...) {theme_grey(...) %+replace% theme(...)}`
